# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='repo-command.proto',
  package='',
  serialized_pb='\n\x12repo-command.proto\"\xb9\x05\n\x1bRepoCommandParameterMessage\x12R\n\x16repo_command_parameter\x18\xc9\x01 \x02(\x0b\x32\x31.RepoCommandParameterMessage.RepoCommandParameter\x1a\x19\n\x04Name\x12\x11\n\tcomponent\x18\x08 \x03(\x0c\x1aY\n\nKeyLocator\x12/\n\x04name\x18\x07 \x01(\x0b\x32!.RepoCommandParameterMessage.Name\x12\x1a\n\x12key_locator_digest\x18\x1d \x01(\x0c\x1a\x1c\n\x07\x45xclude\x12\x11\n\tcomponent\x18\x08 \x03(\x0c\x1a\xe7\x01\n\tSelectors\x12\x1d\n\x15min_suffix_components\x18\r \x01(\r\x12\x1d\n\x15max_suffix_components\x18\x0e \x01(\r\x12M\n\x1cpublisher_public_key_locator\x18\x0f \x01(\x0b\x32\'.RepoCommandParameterMessage.KeyLocator\x12\x35\n\x07\x65xclude\x18\x10 \x01(\x0b\x32$.RepoCommandParameterMessage.Exclude\x12\x16\n\x0e\x63hild_selector\x18\x11 \x01(\r\x1a\xc7\x01\n\x14RepoCommandParameter\x12/\n\x04name\x18\x07 \x01(\x0b\x32!.RepoCommandParameterMessage.Name\x12\x39\n\tselectors\x18\t \x01(\x0b\x32&.RepoCommandParameterMessage.Selectors\x12\x17\n\x0estart_block_id\x18\xcc\x01 \x01(\r\x12\x15\n\x0c\x65nd_block_id\x18\xcd\x01 \x01(\r\x12\x13\n\nprocess_id\x18\xce\x01 \x01(\x04')




_REPOCOMMANDPARAMETERMESSAGE_NAME = descriptor.Descriptor(
  name='Name',
  full_name='RepoCommandParameterMessage.Name',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='component', full_name='RepoCommandParameterMessage.Name.component', index=0,
      number=8, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=138,
  serialized_end=163,
)

_REPOCOMMANDPARAMETERMESSAGE_KEYLOCATOR = descriptor.Descriptor(
  name='KeyLocator',
  full_name='RepoCommandParameterMessage.KeyLocator',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='name', full_name='RepoCommandParameterMessage.KeyLocator.name', index=0,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='key_locator_digest', full_name='RepoCommandParameterMessage.KeyLocator.key_locator_digest', index=1,
      number=29, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=165,
  serialized_end=254,
)

_REPOCOMMANDPARAMETERMESSAGE_EXCLUDE = descriptor.Descriptor(
  name='Exclude',
  full_name='RepoCommandParameterMessage.Exclude',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='component', full_name='RepoCommandParameterMessage.Exclude.component', index=0,
      number=8, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=256,
  serialized_end=284,
)

_REPOCOMMANDPARAMETERMESSAGE_SELECTORS = descriptor.Descriptor(
  name='Selectors',
  full_name='RepoCommandParameterMessage.Selectors',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='min_suffix_components', full_name='RepoCommandParameterMessage.Selectors.min_suffix_components', index=0,
      number=13, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='max_suffix_components', full_name='RepoCommandParameterMessage.Selectors.max_suffix_components', index=1,
      number=14, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='publisher_public_key_locator', full_name='RepoCommandParameterMessage.Selectors.publisher_public_key_locator', index=2,
      number=15, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='exclude', full_name='RepoCommandParameterMessage.Selectors.exclude', index=3,
      number=16, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='child_selector', full_name='RepoCommandParameterMessage.Selectors.child_selector', index=4,
      number=17, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=287,
  serialized_end=518,
)

_REPOCOMMANDPARAMETERMESSAGE_REPOCOMMANDPARAMETER = descriptor.Descriptor(
  name='RepoCommandParameter',
  full_name='RepoCommandParameterMessage.RepoCommandParameter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='name', full_name='RepoCommandParameterMessage.RepoCommandParameter.name', index=0,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='selectors', full_name='RepoCommandParameterMessage.RepoCommandParameter.selectors', index=1,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='start_block_id', full_name='RepoCommandParameterMessage.RepoCommandParameter.start_block_id', index=2,
      number=204, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='end_block_id', full_name='RepoCommandParameterMessage.RepoCommandParameter.end_block_id', index=3,
      number=205, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='process_id', full_name='RepoCommandParameterMessage.RepoCommandParameter.process_id', index=4,
      number=206, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=521,
  serialized_end=720,
)

_REPOCOMMANDPARAMETERMESSAGE = descriptor.Descriptor(
  name='RepoCommandParameterMessage',
  full_name='RepoCommandParameterMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='repo_command_parameter', full_name='RepoCommandParameterMessage.repo_command_parameter', index=0,
      number=201, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_REPOCOMMANDPARAMETERMESSAGE_NAME, _REPOCOMMANDPARAMETERMESSAGE_KEYLOCATOR, _REPOCOMMANDPARAMETERMESSAGE_EXCLUDE, _REPOCOMMANDPARAMETERMESSAGE_SELECTORS, _REPOCOMMANDPARAMETERMESSAGE_REPOCOMMANDPARAMETER, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=23,
  serialized_end=720,
)

_REPOCOMMANDPARAMETERMESSAGE_NAME.containing_type = _REPOCOMMANDPARAMETERMESSAGE;
_REPOCOMMANDPARAMETERMESSAGE_KEYLOCATOR.fields_by_name['name'].message_type = _REPOCOMMANDPARAMETERMESSAGE_NAME
_REPOCOMMANDPARAMETERMESSAGE_KEYLOCATOR.containing_type = _REPOCOMMANDPARAMETERMESSAGE;
_REPOCOMMANDPARAMETERMESSAGE_EXCLUDE.containing_type = _REPOCOMMANDPARAMETERMESSAGE;
_REPOCOMMANDPARAMETERMESSAGE_SELECTORS.fields_by_name['publisher_public_key_locator'].message_type = _REPOCOMMANDPARAMETERMESSAGE_KEYLOCATOR
_REPOCOMMANDPARAMETERMESSAGE_SELECTORS.fields_by_name['exclude'].message_type = _REPOCOMMANDPARAMETERMESSAGE_EXCLUDE
_REPOCOMMANDPARAMETERMESSAGE_SELECTORS.containing_type = _REPOCOMMANDPARAMETERMESSAGE;
_REPOCOMMANDPARAMETERMESSAGE_REPOCOMMANDPARAMETER.fields_by_name['name'].message_type = _REPOCOMMANDPARAMETERMESSAGE_NAME
_REPOCOMMANDPARAMETERMESSAGE_REPOCOMMANDPARAMETER.fields_by_name['selectors'].message_type = _REPOCOMMANDPARAMETERMESSAGE_SELECTORS
_REPOCOMMANDPARAMETERMESSAGE_REPOCOMMANDPARAMETER.containing_type = _REPOCOMMANDPARAMETERMESSAGE;
_REPOCOMMANDPARAMETERMESSAGE.fields_by_name['repo_command_parameter'].message_type = _REPOCOMMANDPARAMETERMESSAGE_REPOCOMMANDPARAMETER
DESCRIPTOR.message_types_by_name['RepoCommandParameterMessage'] = _REPOCOMMANDPARAMETERMESSAGE

class RepoCommandParameterMessage(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class Name(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _REPOCOMMANDPARAMETERMESSAGE_NAME
    
    # @@protoc_insertion_point(class_scope:RepoCommandParameterMessage.Name)
  
  class KeyLocator(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _REPOCOMMANDPARAMETERMESSAGE_KEYLOCATOR
    
    # @@protoc_insertion_point(class_scope:RepoCommandParameterMessage.KeyLocator)
  
  class Exclude(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _REPOCOMMANDPARAMETERMESSAGE_EXCLUDE
    
    # @@protoc_insertion_point(class_scope:RepoCommandParameterMessage.Exclude)
  
  class Selectors(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _REPOCOMMANDPARAMETERMESSAGE_SELECTORS
    
    # @@protoc_insertion_point(class_scope:RepoCommandParameterMessage.Selectors)
  
  class RepoCommandParameter(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _REPOCOMMANDPARAMETERMESSAGE_REPOCOMMANDPARAMETER
    
    # @@protoc_insertion_point(class_scope:RepoCommandParameterMessage.RepoCommandParameter)
  DESCRIPTOR = _REPOCOMMANDPARAMETERMESSAGE
  
  # @@protoc_insertion_point(class_scope:RepoCommandParameterMessage)

# @@protoc_insertion_point(module_scope)
